import {Router} from 'express';import * as authC from './controllers/auth';import * as tx from './controllers/transactions';import * as intel from './controllers/intelligence';import * as demo from './controllers/demo';import * as extra from './controllers/extra';import {auth} from './middleware/auth';
const r=Router();r.post('/auth/register',authC.register);

r.post('/auth/login',authC.login);
r.post('/auth/logout',authC.logout);
r.get('/auth/me',auth,authC.me);
r.get('/transactions',auth,tx.list);
r.post('/transactions',auth,tx.create);
r.post('/transactions/quick',auth,tx.quick);
r.post('/transactions/quick/preview',auth,tx.quickPreview);
r.put('/transactions/:id',auth,tx.update);
r.delete('/transactions/:id',auth,tx.remove);
r.get('/analytics/overview',auth,intel.getOverview);
r.get('/analytics/anomalies',auth,intel.getAnomalies);
r.get('/analytics/categories',auth,extra.categories);
r.get('/analytics/trends',auth,extra.trends);
r.get('/analytics/insights',auth,extra.insights);
r.get('/analytics/recurring',auth,intel.getRecurring);
r.get('/forecast',auth,intel.getForecast);
r.get('/budgets',auth,intel.getBudgets);
r.post('/budgets',auth,extra.createBudget);
r.delete('/budgets/:id',auth,extra.deleteBudget);
r.get('/subscriptions',auth,extra.subscriptions);
r.post('/assistant/query',auth,intel.assistant);
r.post('/demo/load',auth,demo.loadDemo);
export default r;
